<%@ Page Title="Users" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Users.aspx.cs" Inherits="Appointment_System_and_Venue_Reservation.Users" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">
    <div class="card pb-3">
        <div class="container-fluid">
            <div class="card-header mt-5 mb-5" style="background:#666666;">
                <h4 style="color:#ffffff">User List</h4>
            </div>
            <div class="card-card-header">
             <table style="width: 100%; height: 130px">
                    <tr>
                        <td>&nbsp;</td>
                        <td style="width: 318px">
                            Firsname</td>
                        <td>
                            <asp:TextBox ID="TextBox1" runat="server"></asp:TextBox>
                        </td>
                        <td>&nbsp;</td>
                    </tr>
                    <tr>
                        <td style="width: 318px">&nbsp;</td>
                        <td style="width: 318px">Lastname</td>
                        <td style="width: 318px">
                            <asp:TextBox ID="TextBox2" runat="server"></asp:TextBox>
                        </td>
                        <td style="width: 318px">&nbsp;</td>
                    </tr>
                    <tr>
                        <td style="width: 318px; height: 25px;"></td>
                        <td style="width: 318px; height: 25px;">Username</td>
                        <td style="width: 318px; height: 25px;">
                            <asp:TextBox ID="TextBox3" runat="server"></asp:TextBox>
                        </td>
                        <td style="width: 318px; height: 25px;"></td>
                    </tr>
                    <tr>
                        <td style="width: 318px; height: 22px;"></td>
                        <td style="width: 318px; height: 22px;">
                            <asp:Button ID="Button1" runat="server" Text="ADD" Width="120px" OnClick="Button1_Click" />
                        </td>
                        <td style="width: 318px; height: 22px;">
                            <asp:Button ID="Button2" runat="server" Text="Clear" Width="120px" OnClick="Button2_Click" />
                        </td>
                        <td style="width: 318px">&nbsp;</td>
                    </tr>
                    <tr>
                        <td style="width: 318px"></td>
                        <td style="width: 318px">
                            &nbsp;</td>
                        <td style="width: 318px">
                            &nbsp;</td>
                        <td style="width: 318px">&nbsp;</td>
                    </tr>
                </table>
                <asp:GridView ID="userList" runat="server" DataKeyNames="id"  OnRowDataBound="OnRowDataBound"
                OnRowEditing="OnRowEditing" OnRowCancelingEdit="OnRowCancelingEdit" OnRowUpdating="OnRowUpdating"
                OnRowDeleting="OnRowDeleting" EmptyDataText="No records has been added." AutoGenerateEditButton="true"
                ShowHeaderWhenEmpty="true" AutoGenerateDeleteButton="true" Width="100%" Height="200px">
                   <%-- <Columns>
                        <asp:BoundField HeaderText="ID" />
                        <asp:BoundField HeaderText="firstname" />
                        <asp:BoundField HeaderText="LASTNAME" />
                        <asp:BoundField HeaderText="USERNAME" />
                        <asp:BoundField HeaderText="USER_TYPE" />
                        <asp:CommandField ShowEditButton="true" />
                        <asp:CommandField ShowDeleteButton="true" />
                        <asp:BoundField />
                    </Columns>--%>
                    <HeaderStyle BackColor="#666666" ForeColor="White" />
                </asp:GridView>
            </div>
        </div>
        <div class="modal show" tabindex="-1" role="dialog">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title">Modal title</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                <p>Modal body text goes here.</p>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-primary">Save changes</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              </div>
            </div>
          </div>
        </div>
    </div>
    
  

   
</asp:Content>
